# Generated by Django 5.2.5 on 2025-10-24 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_model', models.CharField(default='Unknown CPU', max_length=200)),
                ('gpu_model', models.CharField(default='Unknown GPU', max_length=200)),
                ('ram_gb', models.FloatField(default=0.0)),
                ('storage_gb', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
